# Generated by Django 2.0.4 on 2018-04-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=250)),
                ('album_artist', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.CharField(max_length=1000)),
                ('format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_name', models.CharField(max_length=250)),
                ('single_artist', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.CharField(max_length=1000)),
                ('single_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Album')),
            ],
        ),
        migrations.RemoveField(
            model_name='rings',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Earrings',
        ),
        migrations.DeleteModel(
            name='Rings',
        ),
    ]
