# Generated by Django 2.0.4 on 2018-04-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20180407_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single',
            name='single_album',
        ),
    ]
