# Generated by Django 2.0.4 on 2018-04-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_remove_single_single_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250)),
                ('song_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Album')),
            ],
        ),
    ]
